export const mockFriends = [
  {
    id: 'f1',
    title: 'Rohit',
    status: 'you-owe',
    amount: 1200,
    groups: [
      { title: 'Goa Trip', amount: 700, status: 'you-owe' },
      { title: 'Office Lunch', amount: 500, status: 'you-owe' },
    ],
  },
  {
    id: 'f2',
    title: 'Priya',
    status: 'friend-owe',
    amount: 850,
    groups: [
      { title: 'Movie Night', amount: 300, status: 'friend-owe' },
      { title: 'Birthday Cake', amount: 550, status: 'friend-owe' },
    ],
  },
  {
    id: 'f3',
    title: 'Amit',
    status: 'settled',
    amount: 0,
    groups: [],
  },
  {
    id: 'f4',
    title: 'Meera',
    status: 'you-owe',
    amount: 2200,
    groups: [
      { title: 'Weekend Trip', amount: 1800, status: 'you-owe' },
      { title: 'Coffee Meetup', amount: 400, status: 'you-owe' },
    ],
  },
  {
    id: 'f5',
    title: 'Arjun',
    status: 'friend-owe',
    amount: 1500,
    groups: [
      { title: 'Concert Tickets', amount: 1200, status: 'friend-owe' },
      { title: 'Snacks & Drinks', amount: 300, status: 'friend-owe' },
    ],
  },
  {
    id: 'f6',
    title: 'Neha',
    status: 'you-owe',
    amount: 600,
    groups: [{ title: 'Birthday Party', amount: 600, status: 'you-owe' }],
  },
  {
    id: 'f7',
    title: 'Karan',
    status: 'friend-owe',
    amount: 950,
    groups: [
      { title: 'Dinner at BBQ', amount: 500, status: 'friend-owe' },
      { title: 'Office Coffee', amount: 450, status: 'friend-owe' },
    ],
  },
  {
    id: 'f8',
    title: 'Aisha',
    status: 'friend-owe',
    amount: 750,
    groups: [{ title: 'Team Brunch', amount: 750, status: 'friend-owe' }],
  },
  {
    id: 'f9',
    title: 'Vikram',
    status: 'you-owe',
    amount: 300,
    groups: [{ title: 'Late Night Snacks', amount: 300, status: 'you-owe' }],
  },
  {
    id: 'f10',
    title: 'Sanya',
    status: 'friend-owe',
    amount: 400,
    groups: [{ title: 'Pool Party', amount: 400, status: 'friend-owe' }],
  },
];

export const mockFriendTransactions = {
  f1: {
    id: 'f1',
    name: 'Rohit',
    total: 2000,
    youOwe: 0,
    friendOwe: 2000,
    transactions: [
      {
        id: 't1',
        group: 'Paid by you | Goa Trip',
        title: 'Dinner at beach shack',
        amount: 700,
        status: 'you-owe',
      },
      { id: 't2', group: 'Office Lunch', title: 'Pizza party', amount: 500, status: 'friend-owe' },
      { id: 't3', group: 'Cab Ride', title: 'Airport to hotel', amount: 800, status: 'friend-owe' },
    ],
  },
  f2: {
    id: 'f2',
    name: 'Priya',
    total: 1500,
    youOwe: 1500,
    friendOwe: 0,
    transactions: [
      {
        id: 't4',
        group: 'Movie Night',
        title: 'Multiplex tickets',
        amount: 900,
        status: 'you-owe',
      },
      {
        id: 't5',
        group: 'Birthday Party',
        title: 'Cake & balloons',
        amount: 600,
        status: 'you-owe',
      },
    ],
  },
  f3: {
    id: 'f3',
    name: 'Amit',
    total: 750,
    youOwe: 0,
    friendOwe: 750,
    transactions: [
      { id: 't6', group: 'Cab Ride', title: 'Shared Uber', amount: 400, status: 'friend-owe' },
      { id: 't7', group: 'Snacks', title: 'Evening samosas', amount: 350, status: 'friend-owe' },
    ],
  },
  f4: {
    id: 'f4',
    name: 'Meera',
    total: 2200,
    youOwe: 2200,
    friendOwe: 0,
    transactions: [
      { id: 't8', group: 'Weekend Trip', title: 'Hotel stay', amount: 1800, status: 'you-owe' },
      { id: 't9', group: 'Coffee Meetup', title: 'Starbucks run', amount: 400, status: 'you-owe' },
    ],
  },
  f5: {
    id: 'f5',
    name: 'Arjun',
    total: 1500,
    youOwe: 0,
    friendOwe: 1500,
    transactions: [
      { id: 't10', group: 'Concert', title: 'Band tickets', amount: 1200, status: 'friend-owe' },
      { id: 't11', group: 'Snacks', title: 'Popcorn & drinks', amount: 300, status: 'friend-owe' },
    ],
  },
  f6: {
    id: 'f6',
    name: 'Neha',
    total: 600,
    youOwe: 600,
    friendOwe: 0,
    transactions: [
      { id: 't12', group: 'Birthday Party', title: 'Return gift', amount: 600, status: 'you-owe' },
    ],
  },
  f7: {
    id: 'f7',
    name: 'Karan',
    total: 950,
    youOwe: 0,
    friendOwe: 950,
    transactions: [
      {
        id: 't13',
        group: 'Dinner at BBQ',
        title: 'Family platter',
        amount: 500,
        status: 'friend-owe',
      },
      {
        id: 't14',
        group: 'Office Coffee',
        title: 'Morning brews',
        amount: 450,
        status: 'friend-owe',
      },
    ],
  },
  f8: {
    id: 'f8',
    name: 'Aisha',
    total: 750,
    youOwe: 0,
    friendOwe: 750,
    transactions: [
      {
        id: 't15',
        group: 'Team Brunch',
        title: 'Buffet breakfast',
        amount: 750,
        status: 'friend-owe',
      },
    ],
  },
  f9: {
    id: 'f9',
    name: 'Vikram',
    total: 300,
    youOwe: 300,
    friendOwe: 0,
    transactions: [
      {
        id: 't16',
        group: 'Late Night Snacks',
        title: 'Momos & rolls',
        amount: 300,
        status: 'you-owe',
      },
    ],
  },
  f10: {
    id: 'f10',
    name: 'Sanya',
    total: 400,
    youOwe: 0,
    friendOwe: 400,
    transactions: [
      {
        id: 't17',
        group: 'Pool Party',
        title: 'Drinks & chips',
        amount: 400,
        status: 'friend-owe',
      },
    ],
  },
};
